services:
  postgres:
    image: postgres:17.7-alpine3.22
    container_name: ${POSTGRES_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: backend-botfarm_backend:latest
    build:
      context: ./backend
    container_name: backend
    env_file: .env
    environment:
      API_PATH_PREFIX: ${API_PATH_PREFIX}
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - postgres
#    volumes:
#      - ./backend:/app/backend

  backend-tests:
    build:
      context: .
      dockerfile: tests/Dockerfile
    container_name: backend-tests
    volumes:
      - ./coverage-reports:/app/htmlcov

volumes:
  pgdata: