services:
  botfarm-postgres:
    image: postgres:17.7-alpine3.22
    container_name: ${BOT_POSTGRES_HOST}
    environment:
      POSTGRES_USER: ${BOT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BOT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${BOT_POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: backend-botfarm_backend:latest
    build: ./backend
    container_name: backend
    env_file: .env
    environment:
      API_PATH_PREFIX: ${API_PATH_PREFIX}
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}
      BOT_POSTGRES_DB: ${BOT_POSTGRES_DB}
      BOT_POSTGRES_USER: ${BOT_POSTGRES_USER}
      BOT_POSTGRES_PASSWORD: ${BOT_POSTGRES_PASSWORD}
      BOT_POSTGRES_HOST: ${BOT_POSTGRES_HOST}
      BOT_POSTGRES_PORT: ${BOT_POSTGRES_PORT}
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - botfarm-postgres
    volumes:
      - ./backend:/app/backend

volumes:
  pgdata: