services:
  postgres:
    image: postgres:17.7-alpine3.22
    container_name: ${POSTGRES_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: backend-botfarm_backend:latest
    build: ./backend
    container_name: backend
    env_file: .env
    environment:
      API_PATH_PREFIX: ${API_PATH_PREFIX}
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app/backend

volumes:
  pgdata: